### ISSUE TITLE
XML format returns comma ( , ) where period ( . ) is expected for rates values

### ISSUE THREAD

**Issue by gcoverd** [Formicka/exchangerate.host#104]
Hi there, great API! Especially including the XML option because I use excel which doesn't have native JSON parsing. If you are able to answer this query, without necessarily fixing it (because a workaround is easy), I will donate.  The xml format returns a comma within the rates values e.g. 0,9012 instead of 0.9012. I would expect a period character and not a comma. 
Call:
https://api.exchangerate.host/latest/?symbols=CAD,USD&base=AUD&format=xml

**Comment by gcoverd** [comment]
Donated.

**Comment by arzzen** [comment]
Hi @gcoverd thank you for your donation, your changes were implemented and deployed
