### ISSUE TITLE
curl: (7) Failed to connect to api.exchangerate.host port 443: Connection refused

### ISSUE THREAD

**Issue by liuxingke** [Formicka/exchangerate.host#112]
use curl https://api.exchangerate.host/2022-02-24
got error "curl: (7) Failed to connect to api.exchangerate.host port 443: Connection refused"
how to solve this problem?

**Comment by arzzen** [comment]
@liuxingke  weird, on my side, it's working correct ...

**Comment by sommmen** [comment]
![image](https://user-images.githubusercontent.com/8641495/157434266-9e4b5d46-e8b7-4e59-a373-c3ae5f48357a.png)

works for me
