### ISSUE TITLE
Latest Rates Endpoint sends old data for base = USD

### ISSUE THREAD

**Issue by FrenakTomas** [Formicka/exchangerate.host#113]
For some reason api for the latest exchange rates shows rates from 2022-01-10. I don't feel this is right as it literally says 'Latest Rates'. When using Convert currency endpoint with USD to EUR/ GBP, the date is properly set to today. 

![image](https://user-images.githubusercontent.com/87690510/155748908-2e8c4fef-3df1-47c9-983b-3f4f9c43edc7.png)

**Comment by arzzen** [comment]
Hi, @FrenakTomas  
See notice in the faq section called "Response showing old date" (#55, #75, #62, #59, #64)

```
 API requests are cached by default. You can try to add an additional parameter &v=_actual_date_ in the query, where _actual_date_ enter the day in the format for example Y-m-d (or you can add only hour value). 
```
