### ISSUE TITLE
Docs: add rate limitations

### ISSUE THREAD

**Issue by sommmen** [Formicka/exchangerate.host#118]
Hiya,

The docs hint at rate limitations in the headers:

> API requests made by a throttled user or app will fail. All API requests are subject to rate limits. Real time rate limit usage statistics are described in headers that are included with most API responses once enough calls have been made to an endpoint.

If i hit /symbols i then get:

```
x-ratelimit-limit: 2000
x-ratelimit-remaining: 1999
```

Is this the rate-limit per day or per month? I'd love for some more info on the rate limitations.

**Comment by arzzen** [comment]
hi @sommmen rate-limit are set per hour
