### ISSUE TITLE
Outage

### ISSUE THREAD

**Issue by Mathieuu** [Formicka/exchangerate.host#119]
Hitting a non cached page gives 521 status code in Cloudflare: https://api.exchangerate.host/latest?base=USD&v=321321321

Stab in the dark: Can it be linked to RUB no longer being listed?

**Comment by madhead** [comment]
Conversions between non-ruble currencies are also broken. E.g.: https://api.exchangerate.host/convert?from=USD&to=EUR&amount=1000

**Comment by arzzen** [comment]
I apologize for the temporary outage.
Now everything should work fine.
