### ISSUE TITLE
HIGH PRIORITY: Incorrect result set and date for latest

### ISSUE THREAD

**Issue by roshandash411** [Formicka/exchangerate.host#121]
`https://api.exchangerate.host/latest?base=USD` is giving incorrect results

This url is giving results from random dates for today. Please check your caches. Todays date is 10th april yet rates are of some date on 2021 
<img width="891" alt="image" src="https://user-images.githubusercontent.com/17148898/162609788-74fb67c1-0b5a-4ce9-975b-f0ab24a570f2.png">

So for now I am using `https://api.exchangerate.host/today?base=USD` which seems to give correct result for my use case.

**Comment by arzzen** [comment]
Hi, @roshandash411 
See notice in the faq section called "Response showing old date" (#55, #75, #62, #59, #64, #113)

```
 API requests are cached by default. You can try to add an additional parameter &v=_actual_date_ in the query, where _actual_date_ enter the day in the format for example Y-m-d (or you can add only hour value). 
```

**Comment by roshandash411** [comment]
@arzzen But ideally this should not be the default. Please add it to the documentation itself so that others do not face any issue. Since its always giving old results so people should know that the date parameter needs to always be added to get latest result. Otherwise the meaning of  `latest` does not make sense in the endpoint.
