### ISSUE TITLE
Issue with cache key

### ISSUE THREAD

**Issue by richardscarrott** [Formicka/exchangerate.host#123]
Thanks for sharing this API.

After evaluating the API, I found an issue with the cache key on the /latest endpoint.

It appears the key is too naive meaning one consumer could break the API for everybody else, especially because a standardised cache busting convention is suggested in the docs (?v=YYYY-MM-DD):

```
# 1. Call this on 2022-04-26
curl -s -XGET 'https://api.exchangerate.host/latest?v=2022-04-27'
# EXPECT:  Fx rates for "2022-04-26" (or maybe an error)
# ACTUAL: Fx rates for "2022-04-26"  ✅

# 2. Call this on 2022-04-27
curl -s -XGET 'https://api.exchangerate.host/latest?v=2022-04-27'
# EXPECT: Fx rates for 2022-04-27
# ACTUAL: Fx rates for 2022-04-26 (due to cache hit from yesterdays call with todays date) ❌
```

Unless perhaps you invalidate the cache whenever the latest is updated (although http caching headers suggest it'll be cached for a year)? If not, I guess to workaround this somebody could just pass in a random uuid which no other consumer knows about which would effectively namespace their cache, but I imagine this isn't something you'd want to encourage.

I think the historical endpoint is prob a safer bet for consumers as the date is explicitly used in the cache key from what I can tell:

```
# 1. Call this on 2022-04-26
curl -s -XGET 'https://api.exchangerate.host/2022-04-27'
# EXPECT:  Error
# ACTUAL: Error ✅

# 2. Call this on 2022-04-27
curl -s -XGET 'https://api.exchangerate.host/2022-04-27'
# EXPECT: Fx rates for 2022-04-27
# ACTUAL: Fx rates for 2022-04-27 ✅
```

**Comment by mtotschnig** [comment]
I was also investigating, why I was receiving outdated data in my use of the "lates"t endpoint, and found that is sends back the following cache-control header:
cache-control: max-age=31536000
which leads okhttp library on Android to use cached answer. I'll probably find out how to have okhttp not rely on this header, but 
wouldn't it make sense to send back a shorter value here, like a day, or some duration that corresponds to the frequency of the service being updated?

**Comment by arzzen** [comment]
API requests are cached by default. You can try to add an additional parameter &v=_actual_date_ in the query, where _actual_date_ enter the day in the format for example Y-m-d (or you can add only hour value).
