### ISSUE TITLE
Historical data seems to be down

### ISSUE THREAD

**Issue by pac421** [Formicka/exchangerate.host#124]
Hi,

The historical rate API always return response 521, for any request including the documentation example: 
https://api.exchangerate.host/2020-04-04

I hope it was only the historical rate endpoint so I tried to get the same data by using the convert endpoint, and this one is working good:
https://api.exchangerate.host/convert?from=USD&to=EUR

..except when a date argument is used:
https://api.exchangerate.host/convert?from=USD&to=EUR&date=2020-04-04

It seems to be the historical data which is broken. I didn't find any info if the team is currently working on or not so I post this ticket and hope it will help you to know :)

Thank you for sharing this insane API !

**Comment by arzzen** [comment]
@pac421 it already works, sorry for the temporary outage ;)

**Comment by pac421** [comment]
Oh nice thanks !
