### ISSUE TITLE
Receiving incorrect EURO value

### ISSUE THREAD

**Issue by Minibumphead** [Formicka/exchangerate.host#125]
When making a request to "https://api.exchangerate.host/latest?base=USD" I get the wrong currency value for EUR.

Here is the code I'm running in a simple Python script.

`import requests
import json

res = requests.get("https://api.exchangerate.host/latest?base=USD"
rate = res["rates"]["EUR"]
print(rate)
`

This prints a value of either 0.8811185976821294 or 0.9514041774254622. The second value seems to be valid but the first value is way off. Any ideas?

**Comment by goaround** [comment]
Found a solution: add the current date as the v-parameter: `&v=2022-04-29`

E.g. https://api.exchangerate.host/latest?base=USD&v=2022-04-29

**Comment by Minibumphead** [comment]
Let me try this. Thanks :)

Johannes Kinast ***@***.***> schrieb am Fr., 29. Apr. 2022,
12:43:
