### ISSUE TITLE
Discrepancy with market value

### ISSUE THREAD

**Issue by fe-dagostino** [Formicka/exchangerate.host#126]
url = 'https://api.exchangerate.host/latest?base=USD&symbols=ETH&amount=1&source=crypto'

result 

{'motd': {'msg': 'If you or your company use this project or like what we doing, please consider backing us so we can continue maintaining and evolving this project.', 'url': 'https://exchangerate.host/#/donate'}, 'success': True, 'base': 'USD', 'date': '2022-04-28', 'rates': {'ETH': 2614.019869}}

Value for ETH at 28 April 2022 is 2832.4902 USD, so there is discrepancy is more than 200 USD

**Comment by alerque** [comment]
First of all, you are comparing apples and oranges. You are comparing a current market rate to a "day" value which is usually a close of day or midnight UTC value, but for a day that isn't even finished who knows what you are even comparing. You need to compare exact time stamps.

Secondly, most cryptocurrency exchange rates are super volatile and they vary significantly between different exchanges at any given moment (e.g. BTC sometimes varies by much more than $200 between exchanges). There are several different sources in this API. Use the one you want to reference and understand that only the exchange itself is authoritative at any given moment and only valid for exchanges on *their* platform. A different exchange may give you a different rate.

These points are actually true for fiat currencies as well, it is just much less noticeable.
