### ISSUE TITLE
Precise range of available historical rates

### ISSUE THREAD

**Issue by stevecondylios** [Formicka/exchangerate.host#13]
> Historical rates are available for most currencies all the way back to the year of 1999.

I guess most currencies' first available day's data are: `1999-01-01`, but there may be a need to find the first available date for those which aren't available from that date. Is there a call to grab the earliest available historical rate for a particular currency (or all currencies)?

**Comment by asvvvad** [comment]
I found it to be 1999-01-04 (YYYY-MM-DD) but it may not be the case for all currencies

**Comment by stevecondylios** [comment]
@asvvvad good pick up! I hadn't tested - only assumed `01-01`. It would be great to know the start date for each currency. I guess that would be small object with around 200 values (as many values as currencies). 

Do you know if there's an easy way to retrieve that? (we could iterate through each currency's historical data, but I guess others may need it too, so may be worth it being made available via an API call).

**Comment by asvvvad** [comment]
Yes I agree, don't know any way to do it so gotta wait for @Formicka I guess

**Comment by arzzen** [comment]
Hi everyone, thank you for your feature requests (added to my to-do list).
Now it's hard to say when this feature will be deployed, but soon!

btw:
Why are you querying one-by-one by date when we have time-series endpoint (maximum date range one year)?
You can query by year frame window instead of the number of days each year...
eg: https://api.exchangerate.host/timeseries?start_date=2019-01-01&end_date=2019-12-31

**Comment by stevecondylios** [comment]
@arzzen re: adding to to-do list - that's awesome.

Regarding queries with long date ranges, I wrote R function `make_dates()` to easily convert a long time period into multiple smaller periods of 365 days or less. 

Here's an example

```R
# Run once to install
# install.packages("priceR")

library(priceR)
start_date = "2010-01-01"
end_date = "2020-06-30"
n_days = 365
priceR:::make_dates(start_date, end_date, n_days)

   start_date   end_date
1  2010-01-01 2011-01-01
2  2011-01-01 2012-01-01
3  2012-01-01 2012-12-31
4  2012-12-31 2013-12-31
5  2013-12-31 2014-12-31
6  2014-12-31 2015-12-31
7  2015-12-31 2016-12-30
8  2016-12-30 2017-12-30
9  2017-12-30 2018-12-30
10 2018-12-30 2019-12-30
11 2019-12-30 2020-06-30

```

`make_dates()` is used inside `historical_exchange_rates()` to grab many years' data in [one function call](https://github.com/stevecondylios/priceR#retrieve-historical-exchange-rates) (it makes as many API calls as is necessary under the hood). 

### Example

This will return all the AUD to USD rates between 2010 and 2020 with one function call. 

```R
historical_exchange_rates("AUD", to = "USD",
                          start_date = "2010-01-01", end_date = "2020-06-30")

           date one_AUD_equivalent_to_x_USD
1    2010-01-01                    0.898084
2    2010-01-02                    0.898084
3    2010-01-03                    0.898084
4    2010-01-04                    0.912623
5    2010-01-05                    0.912011
6    2010-01-06                    0.920736
...
3829 2020-06-25                    0.688899
3830 2020-06-26                    0.686340
3831 2020-06-27                    0.686340
3832 2020-06-28                    0.685910
3833 2020-06-29                    0.687335
3834 2020-06-30                    0.690166

```

The reason I'm interested in the earliest available date for each currency is so I can give the user a useful message when they request data that the API doesn't contain.

**Comment by arzzen** [comment]
@stevecondylios fyi I've updated the response to the resource and added the available_from_date attribute (which represents the start collecting date of the data), see https://api.exchangerate.host/sources.
