### ISSUE TITLE
Server is down

### ISSUE THREAD

**Issue by Daninet** [Formicka/exchangerate.host#130]
I'm trying
GET https://api.exchangerate.host/latest?symbols=GBP&base=SEK

**Comment by Daninet** [comment]
<img width="749" alt="image" src="https://user-images.githubusercontent.com/884882/167415528-cfeebded-ee5b-4afd-94c0-cb137d8904e1.png">

**Comment by Conparator** [comment]
For me too. I recognized that it seems to only affect the crypto currency-source.
I tested the following:
Converting from EUR to USD works.
Converting from EUR to SOL/ETH/BTC etc. doesn't work.
Converting from cryptocurrency to cryptocurrency doesn't work too.

**Comment by dinbrca** [comment]
same same , your status page doesn't convey the status of the API service correctly, you have status for the latest rates (which work well) but when trying a specific currency to currency - it fails - see pictures

<img width="1408" alt="Screen Shot 2022-05-09 at 17 46 16" src="https://user-images.githubusercontent.com/2164032/167435776-bd14fda7-7ac7-4a48-9a85-c2de1b065699.png">

<img width="1408" alt="Screen Shot 2022-05-09 at 17 46 07" src="https://user-images.githubusercontent.com/2164032/167435749-a0a72ff0-7f8f-49a9-9a85-9b057761066f.png">

**Comment by arzzen** [comment]
I apologize for the temporary outage on the server provider's side (network issue)

**Comment by Conparator** [comment]
> I apologize for the temporary outage on the server provider's side (network issue)

Ah, ok. From my POV there is no need to apologize from your side :)
