### ISSUE TITLE
Not identical rates if request for different decimals

### ISSUE THREAD

**Issue by artexhibit** [Formicka/exchangerate.host#135]
I use the next endpoint: [https://api.exchangerate.host/latest?base=EUR&places=4&v=1](CLICK)

When I request 4 decimal places, API returns the number: AED: 3.8831
When I request 8 decimal places, API returns different number: AED: 3.9312798

This is fair for other currencies.

Why is that so?

**Comment by alerque** [comment]
Did you use the cache buster to avoid getting a cached result for both values? You kind of have to do that with that with the `latest` endpoint. Historical values are quite useful cached but the latest one you are going to get the value at whatever time somebody first requested the particular combo...

**Comment by artexhibit** [comment]
> Did you use the cache buster to avoid getting a cached result for both values? You kind of have to do that with that with the `latest` endpoint. Historical values are quite useful cached but the latest one you are going to get the value at whatever time somebody first requested the particular combo...

Nope, I didn't use the cache buster... I am learning SWIFT, and found the API to use in my first app. Can you please tell me what should I do to receive an identical values with a little bit more details because I don't know of how to implement a cache buster here...?

**Comment by alerque** [comment]
From the [home page](https://exchangerate.host/):

> Response showing old date
>
> API requests are cached by default. You can try to add an additional parameter &v=_actual_date_ in the query, where _actual_date_ enter the day in the format for example Y-m-d (or you can add only hour value).

**Comment by artexhibit** [comment]
> From the [home page](https://exchangerate.host/):
> 
> > Response showing old date
> > API requests are cached by default. You can try to add an additional parameter &v=_actual_date_ in the query, where _actual_date_ enter the day in the format for example Y-m-d (or you can add only hour value).

Oh yes, I saw that. And in my endpoint I added "&v=1" at the end. But it seems it was wrong...
