### ISSUE TITLE
Blocked by CORS policy today

### ISSUE THREAD

**Issue by maysaleba** [Formicka/exchangerate.host#137]
Hello using 
https://api.exchangerate.host/latest?base=PHP&v=2022-06-02T21 but i'm getting the error below

![image](https://user-images.githubusercontent.com/80749020/171600726-a88280b9-b768-4201-91fb-a23d060ba0a2.png)

**Comment by dorep** [comment]
Same issue.

**Comment by lunga-mxhalisa** [comment]
Something probably related on my side as well. I'm getting a timeout error
![Screenshot 2022-06-02 at 12 24 24](https://user-images.githubusercontent.com/19879968/171609935-9e385663-492c-4e92-a42b-03d89e304d84.png)

**Comment by SerkisExclusive** [comment]
Same here, and suddenly the service become very slow on response

**Comment by arzzen** [comment]
Sorry for temporary outage, due to high voltage power supply failure in the main datacenter...
https://status.master.cz/en/history
