### ISSUE TITLE
Historical Rates Endpoint neglecting optional parameters

### ISSUE THREAD

**Issue by fenchai23** [Formicka/exchangerate.host#139]
this is an example of Historical Rates Enpoint api call (neglected optional pars):

`https://api.exchangerate.host/2022-06-13&base=USD&symbols=USD,CNY,CAD`
[Historical Rates Enpoint](https://api.exchangerate.host/2022-06-13&base=USD&symbols=USD,CNY,CAD)

and this is an example for Timeseries Endpoint api call (optional pars works):

`https://api.exchangerate.host/timeseries?start_date=2022-06-13&end_date=2022-06-13&base=USD&symbols=USD,CNY,CAD`
[Timeseries Endpoint](https://api.exchangerate.host/timeseries?start_date=2022-06-13&end_date=2022-06-13&base=USD&symbols=USD,CNY,CAD)

Am I inputting this incorrectly?

**Comment by artexhibit** [comment]
Same problem...
