### ISSUE TITLE
API is down

### ISSUE THREAD

**Issue by AMG22075** [Formicka/exchangerate.host#140]
Example:
https://api.exchangerate.host/latest?source=ecb&base=USD&symbols=USD,AUD

**Comment by tractorcow** [comment]
Oddly, the status page doesn't reflect this? https://exchangerate.host/#/status

**Comment by AMG22075** [comment]
I did some test by just changing the symbol

Work fine:
https://api.exchangerate.host/latest?base=USD&symbols=JPY
https://api.exchangerate.host/latest?base=USD&symbols=CAD

Do not work (error 521):
https://api.exchangerate.host/latest?base=USD&symbols=CNY
https://api.exchangerate.host/latest?base=USD&symbols=SGD

**Comment by tractorcow** [comment]
If it's cloudflare caching a successful result, the backend service could still be down, but some results are available.

**Comment by arzzen** [comment]
I apologize for the "blackout", the service is running .

**Comment by tractorcow** [comment]
thanks @arzzen appreciate the update :)

**Comment by AMG22075** [comment]
Thank you very much.
