### ISSUE TITLE
https://api.exchangerate.host/convert?from=JPY&to=RUB&source=cbr      RETURN NULL

### ISSUE THREAD

**Issue by babahvl** [Formicka/exchangerate.host#143]
https://api.exchangerate.host/convert?from=JPY&to=RUB&source=cbr

RESULT
{"from":"JPY","to":"RUB","amount":1},"info":{"rate":null},"historical":false,"date":"2022-06-27","result":null}

**Comment by babahvl** [comment]
not work
result null

**Comment by arzzen** [comment]
hi @babahvl  use base parameter not source eg:
https://api.exchangerate.host/convert?from=JPY&to=RUB&base=cbr
