### ISSUE TITLE
The USD rate returned by API doesn't match the one shown on the European Central Bank website

### ISSUE THREAD

**Issue by dmustafic-datafin** [Formicka/exchangerate.host#147]
The same goes for the rest of the currencies. They match just in the first decimal position. 

Data from API:
```
https://api.exchangerate.host/latest?base=EUR&symbols=USD&source=ecb
"success": true,
    "base": "EUR",
    "date": "2022-07-05",
    "rates": {
        "USD": 1.0455
    }
```

Data from [ECB Euro foreign exchange reference rates](https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html)

```
<Cube>
  <Cube time="2022-07-05">
    <Cube currency="USD" rate="1.0290"/>
```

**Comment by sal0max** [comment]
Could be one of those causes:
1. Caching issue. See https://github.com/Formicka/exchangerate.host/issues/123
2. Refresh time: ECB updates around 16:00 CET, where this API probably runs around midnight UTC, I guess. So there can be some delay.

Whatever it is: For me, right now (23:44 UTC), the values match exactly.
