### ISSUE TITLE
Historical Rated | Date Problem

### ISSUE THREAD

**Issue by baka195** [Formicka/exchangerate.host#148]
https://api.exchangerate.host/2020-04-04&symbols=USD

Not show only USD currency but all currencies

**Comment by sal0max** [comment]
You made a mistake in your request. As the `symbols` is the first parameter of this url, it needs to lead with `?`, not `&`.

Then it works: https://api.exchangerate.host/2020-04-04?symbols=USD

**Comment by baka195** [comment]
Thank you very much!!!!
