### ISSUE TITLE
source=ecb returns {"success":false}

### ISSUE THREAD

**Issue by AMG22075** [Formicka/exchangerate.host#151]
Hello and thank you for this API.

The `source=ecb` is apparently not working at the moment.
Example: 
https://api.exchangerate.host/latest?source=ecb&base=USD&symbols=USD,AUD,CAD,CHF,CNY,EUR,GBP,HKD,JPY,SGD

Please advise.

**Comment by arzzen** [comment]
@AMG22075 thank you for the report, ecb introduced a captcha over the xml data, our api was modified and it works like a charm
