### ISSUE TITLE
incorrect rate in euro when calls 2-3 times same api

### ISSUE THREAD

**Issue by rishabh3354** [Formicka/exchangerate.host#152]
[](url)import requests

        url = "https://api.exchangerate.host/latest?base=USD"
        response = requests.get(url)
        data = supported_currency(response.json())

data : screen shot atta
![Screenshot from 2022-07-13 09-58-00](https://user-images.githubusercontent.com/26843758/178654425-3e56f157-b964-4ada-9355-1cc496887d4c.png)
ched

last 2 records shows euro rate vs usd is incorrect

[9:55 AM, 7/13/2022] Rishabh Bhardwaj: [{'country_name': 'Euro', 'symbol': '€', 'abbr': 'EUR', 'rate': 0.996818}
[9:55 AM, 7/13/2022] Rishabh Bhardwaj: [{'country_name': 'Euro', 'symbol': '€', 'abbr': 'EUR', 'rate': 0.883011},

this is not accepted as this data is absolutely incorrect. yet it is free but not acceptable

i changed my exchange rate provider now.

please fix this serious issue
thanks

**Comment by arzzen** [comment]
it seems that it will be a cache problem, try adding some GET parameter for break the cache
