### ISSUE TITLE
Is there a way to get the last update time?

### ISSUE THREAD

**Issue by ozgurg** [Formicka/exchangerate.host#153]
Hi.
When we make a GET request to the API, it responds as follows:

```json
{
  "motd": {
    "msg": "If you or your company use this project or like what we doing, please consider backing us so we can continue maintaining and evolving this project.",
    "url": "https://exchangerate.host/#/donate"
  },
  "success": true,
  "base": "USD",
  "date": "2022-07-13",
  "rates": {
    "TRY": 17.321539
  }
}
```

As you can see the date (2022-07-13) is in the formatted YYYY-MM-DD.
Is there a way to get the last update time with hours and minutes?

The API is not updated instantly, so I want to notify the user when it was last updated.

**Comment by arzzen** [comment]
data is updated 5 minutes after midnight, ecb source update are after 4 p.m (UTC time)
