### ISSUE TITLE
old ecb exchange rate

### ISSUE THREAD

**Issue by tREybex** [Formicka/exchangerate.host#155]
if I call the latest exchange rate from eur to usd from source ecb
`/latest?base=EUR&symbols=USD&source=ecb`
I got this result:
{
    "motd": {
        "msg": "If you or your company use this project or like what we doing, please consider backing us so we can continue maintaining and evolving this project.",
        "url": "https://exchangerate.host/#/donate"
    },
    "success": true,
    "base": "EUR",
    "date": "2022-07-19",
    "rates": {
        "USD": 1.0131
    }
}
that's the same result as yesterday
`/2022-07-18/?base=EUR&symbols=USD&source=ecb`
{
    "motd": {
        "msg": "If you or your company use this project or like what we doing, please consider backing us so we can continue maintaining and evolving this project.",
        "url": "https://exchangerate.host/#/donate"
    },
    "success": true,
    "historical": true,
    "base": "EUR",
    "date": "2022-07-18",
    "rates": {
        "USD": 1.0131
    }
}

on which time, I get the offical exchange rate from ecb?

**Comment by arzzen** [comment]
Hi @tREybex ECB are based on a regular daily concertation procedure between central banks across Europe, which normally takes place at 14:15 CET. 

ps:
API requests are cached by default. You can try to add an additional parameter &v=_actual_date_ in the query, where _actual_date_ enter the day in the format for example Y-m-d (or you can add only hour value).
