### ISSUE TITLE
Rate limit remaining requests in the header response are not udpateing

### ISSUE THREAD

**Issue by NikolayChankov2445** [Formicka/exchangerate.host#164]
I am currently researching API for exchange rates and noticed that rate limit usage statistics  described in headers are not updating . 
The base is 2000 calls , but is this for monthly basis ?  

Also , the remaining calls limit is always on 1998 , which is a bit confusing and can not track if you are going to be rate limited soon . 

Any suggestions.

**Comment by luxalpa** [comment]
Having the same problem here. Was interested in using it, but without the ability to know whether that's even possible, I'll have to look elsewhere.

**Comment by arzzen** [comment]
Hi @NikolayChankov2445 and @luxalpa rate limit request are 2000 per IP per minute, but API requests are cached by default. You can try to add an additional parameter &v=_actual_date_ in the query, where _actual_date_ enter the day in the format for example Y-m-d (or you can add only hour value).
