### ISSUE TITLE
Hitting 502s when trying to fetch currency rates starting Sept 1 2022

### ISSUE THREAD

**Issue by kevinleehsu** [Formicka/exchangerate.host#170]
We've been pretty consistently hitting 502s when trying to fetch currency rates starting sept 1. This is the base url we are making the request through: https://api.exchangerate.host/2022-09-29?base=EUR Is there a way we can get better visibility into what's causing this?

**Comment by arzzen** [comment]
Hi @kevinleehsu , we do not see any major problem when querying the API, please, 
if the problem persists on your side, try our another hostname (server are located on different provider & location)

https://api-us.exchangerate.host/
https://api-eu.exchangerate.host/
