### ISSUE TITLE
Incorrect currency conversion data

### ISSUE THREAD

**Issue by doroved** [Formicka/exchangerate.host#172]
### The API provides incorrect data. Here is an example of RUB to USD conversion.

**https://api.exchangerate.host/convert?from=RUB&to=USD&ts=1666660691**
<img width="250" alt="image" src="https://user-images.githubusercontent.com/30116541/197659676-9db4c970-dfd4-4a12-9c50-71f8edf16219.png">
"rate": 0.016139
**1/0.016139 = 61.96**

**fixer-api**
<img width="282" alt="image" src="https://user-images.githubusercontent.com/30116541/197659821-20c653fc-afcd-4b72-8621-20be298740b9.png">
"rate": 0.016326,
**1/0.016326 = 61.25**

USD to RUB google
<img width="363" alt="image" src="https://user-images.githubusercontent.com/30116541/197660011-3d541f74-cfcd-4d66-913d-48cf6d870695.png">

**Comment by arzzen** [comment]
hi, it seems to be correct (forex exchange rate changes during an active trading day, so the value fluctuates)

1 rub = 0.016x usd
https://api.exchangerate.host/convert?from=RUB&to=USD&amount=1&date=2022-10-25

1 usd = 61.x rub 
https://api.exchangerate.host/convert?from=USD&to=RUB&amount=1&date=2022-10-25

**Comment by doroved** [comment]
> hi, it seems to be correct (forex exchange rate changes during an active trading day, so the value fluctuates)
> 
> 1 rub = 0.016x usd https://api.exchangerate.host/convert?from=RUB&to=USD&amount=1&date=2022-10-25
> 
> 1 usd = 61.x rub https://api.exchangerate.host/convert?from=USD&to=RUB&amount=1&date=2022-10-25

Yes, I noticed this message in the repository: "Rates are updated around midnight UTC every working day."
Now I see why the rates may be different from the current rate at the moment.
