### ISSUE TITLE
Web server is down

### ISSUE THREAD

**Issue by ignacio-dev** [Formicka/exchangerate.host#174]
I am trying to use your API but it seems like your server is down.

**Comment by arzzen** [comment]
@ignacio-dev  hi, it was a short-term outage, the system was being updated and restarted. Currently, everything should work. 
In case of persistent problem, try alternative host api-eu.exchangerate.host or api-us.exchangerate.host

**Comment by ignacio-dev** [comment]
Thank you for such quick response! Everything is working great now.
