### ISSUE TITLE
Cool API

### ISSUE THREAD

**Issue by wescosmic** [Formicka/exchangerate.host#176]
Hi nice service! We're using your api to bring prices of Caribbean currencies on Tron blockchain to support a stablecoin protocol called goStables. We also entered this into the current Tron Hackathon - 
https://devpost.com/software/gostables
https://forum.trondao.org/t/gostables-decentralized-stablecoins-for-the-caribbean/10842

Referenced you all in our docs:
https://docs.gostables.org/getting-started/price-feeds

Maybe we can collab to bring more real world price data onto the Tron blockchain? :)

///////////

Thanks

**Comment by arzzen** [comment]
Hi @wescosmic , thank you for reaching us, we appreciate it ;).
We will be happy if you continue to use our API. We will try to be as helpful as possible, but our working hours are limited.
