### ISSUE TITLE
[Query] Currency Conversion API Service

### ISSUE THREAD

**Issue by Paramjeet098** [Formicka/exchangerate.host#177]
Hi 
I am Paramjeet, on behalf of Tracxn Technologies Limited. We provide data of private companies to our clients.
We have come across your currency conversion API service which solves our use case. But before using your service we have some queries that we want to clarify. If you can answer the below questions it will be helpful;
1/ We have financials and funding rounds data available on our platform. A lot of users want to see the numbers in a different currency. Can we convert the numbers using your service?
2/ We have some use-cases where we want to use the average value of a currency for a specific month or year. For this we want to store currency conversion data for each date in our database and want to use this. Can we store your data in our database?
3/ We want to get the time-series data till 1999. How many API calls are required for this?

Waiting for your reply.

Thanks & Regards
Paramjeet

**Comment by arzzen** [comment]
Hi @Paramjeet098 ,
our API service is available for free, so:
1) yes,
2) yes, there are no restrictions,
3) max day range for time-series endpoint are 366 days (see #67).

There are no limits to API requests, but please try to cache each request to speed up your & our application.
