### ISSUE TITLE
All sources except ecb do not seem to work

### ISSUE THREAD

**Issue by tincann** [Formicka/exchangerate.host#18]
Hi @arzzen ,

We're considering using this in our applications. To me, it's crazy that you offer this for free, so we're considering donating to you. One small question: for our application, it's important to know from which source the rate originates. 

It seems that all sources that are listed under `https://api.exchangerate.host/sources` all do not work, except for `ecb`.

For example, if I choose `source=imf`, I get 0 rates back.
> https://api.exchangerate.host/timeseries?start_date=2020-01-01&end_date=2020-01-10&source=imf

If I choose `source=ecb`, then it works as expected.
> https://api.exchangerate.host/timeseries?start_date=2020-01-01&end_date=2020-01-10&source=ecb

If I exclude `source=...` from the query, then I get more symbols back than if I would've chosen `ecb`.
> https://api.exchangerate.host/timeseries?start_date=2020-01-01&end_date=2020-01-10

The problem is that we need the rates for a symbol that is not included in `ecb`, but we would also like to know what its source is. 

Thank you!

**Comment by arzzen** [comment]
Hi @tincann 

First of all, thanks for your considering to use our API, I appreciate your offer!

Some API resources are available from a specific date when data collection began.
For now, I've updated the response to the resource and added the `available_from_date` attribute (which represents the start collecting date of the data), see https://api.exchangerate.host/sources.

I may update the older data in the future, but it's hard to say when it will be done!

**Comment by tincann** [comment]
Hi @arzzen 

Thanks for your quick answer! Now I understand why specific sources do not return rates. I still have one question left, however.

If I perform a query on a certain date range without specifying the source,
> https://api.exchangerate.host/timeseries?start_date=2015-01-01&end_date=2015-01-10

I get rates back for symbols like `CLP`, for example. These do not come from the ECB (as they don't offer rates for that symbol), but from some source not listed in `/sources` it seems. Could you clarify that?

**Comment by arzzen** [comment]
> 
> 
> Hi @arzzen
> 
> Thanks for your quick answer! Now I understand why specific sources do not return rates. I still have one question left, however.
> 
> If I perform a query on a certain date range without specifying the source,
> 
> > https://api.exchangerate.host/timeseries?start_date=2015-01-01&end_date=2015-01-10
> 
> I get rates back for symbols like `CLP`, for example. These do not come from the ECB (as they don't offer rates for that symbol), but from some source not listed in `/sources` it seems. Could you clarify that?

the default source is forex rates

![obrázok](https://user-images.githubusercontent.com/6382002/91654922-2fc67b00-eaad-11ea-8a5a-7ee4449361a8.png)

**Comment by tincann** [comment]
@arzzen Understood. Which source do you use for the forex rates? And what type of metric (bid, ask, mid-rate, etc)? The reason I'm asking is that in our application we need the data to be able to be traced back to the original source, for transparency sake.

**Comment by arzzen** [comment]
> @arzzen Understood. Which source do you use for the forex rates? And what type of metric (bid, ask, mid-rate, etc)? The reason I'm asking is that in our application we need the data to be able to be traced back to the original source, for transparency sake.

Sources include banks and financial data providers. All exchange rate data are delivered in midpoint data. Midpoint rates are determined by calculating the average median rate of Bid and Ask at a certain time.

**Comment by lequangminh** [comment]
> > Hi @arzzen
> > Thanks for your quick answer! Now I understand why specific sources do not return rates. I still have one question left, however.
> > If I perform a query on a certain date range without specifying the source,
> > > https://api.exchangerate.host/timeseries?start_date=2015-01-01&end_date=2015-01-10
> > 
> > 
> > I get rates back for symbols like `CLP`, for example. These do not come from the ECB (as they don't offer rates for that symbol), but from some source not listed in `/sources` it seems. Could you clarify that?
> 
> the default source is forex rates
> 
> ![obrázok](https://user-images.githubusercontent.com/6382002/91654922-2fc67b00-eaad-11ea-8a5a-7ee4449361a8.png)

Please anwser my question
the default source is forex rates

**Comment by lequangminh** [comment]
> Sources include banks and financial data providers.


Can you tell me the details of this source?
For example, which bank, financial institution, or website to refer to.
