### ISSUE TITLE
Symbols params doesn't work

### ISSUE THREAD

**Issue by krevedkin** [Formicka/exchangerate.host#192]
Api call:
https://api.exchangerate.host/latest?base=EUR&symbols=EUR,USD,AMD,RUB,AZN,BYN,KZT,KGS,MDL,TJS,TMT,UZS,UAH
<img width="1162" alt="Снимок экрана 2022-12-28 в 04 08 32" src="https://user-images.githubusercontent.com/70909877/209738391-3403a9a1-3cf8-433a-8c6c-013a1fa9e253.png">

**Comment by firephantomassasin** [comment]
same issue with here: https://github.com/Formicka/exchangerate.host/issues/193
