### ISSUE TITLE
Timeseries endpoint is not working

### ISSUE THREAD

**Issue by sebastiandve** [Formicka/exchangerate.host#193]
`https://api.exchangerate.host/timeseries?start_date=2020-01-01&end_date=2020-04-04&symbols=EUR,USD,GBP` returns error code 521

**Comment by jerrywoo96** [comment]
more likely server is down. I also cant access https://api.exchangerate.host/convert?from=SGD&to=CNY&base=SGD

![image](https://user-images.githubusercontent.com/26324139/209749108-c4ea389c-848f-4990-a37d-382a127c3b8d.png)

**Comment by firephantomassasin** [comment]
Same here i cannot access the ff api:

[GetLatestOrPastRateFromExchangeRatesApi](https://api.exchangerate.host/latest?base=USD&symbols=USD,EUR,CZK)

**Comment by vosylienthanh** [comment]
Same for me, I can't access
[https://api.exchangerate.host/2022-12-26?base=USD](https://api.exchangerate.host/2022-12-26?base=USD)
