### ISSUE TITLE
404 failures when requesting a USD base

### ISSUE THREAD

**Issue by iKadmium** [Formicka/exchangerate.host#196]
Currently, calling the [latest endpoint with a base query param of USD](https://api.exchangerate.host/latest?base=USD) returns a 404, with a `{success: false}` body.

**Comment by arzzen** [comment]
works fine on my side https://api.exchangerate.host/latest?base=USD&v=321321321

**Comment by iKadmium** [comment]
Nice, works for me too now. Must have been a short blip 🤷 . Sorry for the false alarm.
