### ISSUE TITLE
connection timeout, banned

### ISSUE THREAD

**Issue by ideea** [Formicka/exchangerate.host#200]
for some reason i’m getting connection timeout for last week or two. how can we fix it?

**Comment by arzzen** [comment]
Hi you can try fetch data via different ip or use vpn, or you can use our another host:
 api-eu.exchangerat.host 
 api-us.exchangerate.host

**Comment by ideea** [comment]
or maybe there's a way to unban me and find out why am I banned? :)

changing host doesn't help.

**Comment by arzzen** [comment]
it's weird, we don't have any restrictions/blaclists, can you give me your ip?

**Comment by ideea** [comment]
157.90.170.70

it might be Cloudflare ban

**Comment by arzzen** [comment]
as I say, we don't block any IPs or countries, we don't have any restrictions on WAF, but I whitelisted your IP (it may helps)
