### ISSUE TITLE
USD to AED result is coming as Null

### ISSUE THREAD

**Issue by bala1991** [Formicka/exchangerate.host#207]
https://api.exchangerate.host/convert?from=USD&to=AED 

When i try to call the above API. I am getting the response as Null.

{"motd":{"msg":"If you or your company use this project or like what we doing, please consider backing us so we can continue maintaining and evolving this project.","url":"https://exchangerate.host/#/donate"},"success":true,"query":{"from":"USD","to":"AED","amount":1},"info":{"rate":null},"historical":false,"date":"2023-03-13","result":null}

**Comment by arzzen** [comment]
Hello @bala1991, today we had a temporary failure to update some currencies.
We solved the problem and now everything is fine, see https://github.com/Formicka/exchangerate.host/issues/209
