### ISSUE TITLE
EUR to PKR rate is null

### ISSUE THREAD

**Issue by tmsperera** [Formicka/exchangerate.host#208]
https://api.exchangerate.host/convert?from=EUR&to=PKR

When i try to call the above API. I am getting the response rate as `null`.

`{"motd":{"msg":"If you or your company use this project or like what we doing, please consider backing us so we can continue maintaining and evolving this project.","url":"https://exchangerate.host/#/donate"},"success":true,"query":{"from":"EUR","to":"PKR","amount":1},"info":{"rate":null},"historical":false,"date":"2023-03-13","result":null}%`

**Comment by arzzen** [comment]
Hello @tmsperera , today we had a temporary failure to update some currencies. 
We solved the problem and now everything is fine, see #209
