### ISSUE TITLE
Incorrect rates for some currency pairs prior to 2 May 2020

### ISSUE THREAD

**Issue by stevecondylios** [Formicka/exchangerate.host#24]
There are some strange results being returned for some currency pairs that include the `BTN` currency. 

For example, for the  `BTN` to `SGD` rates (https://api.exchangerate.host/timeseries?start_date=2020-04-28&end_date=2020-05-03&base=BTN&symbols=SGD), we see:

```js
{"success":true,"timeseries":true,"base":"BTN","start_date":"2020-04-28","end_date":"2020-05-03","rates":{"2020-04-28":{"SGD":1.537},"2020-04-29":{"SGD":1.5345},"2020-04-30":{"SGD":1.5338},"2020-05-01":{"SGD":0.018711},"2020-05-02":{"SGD":0.018855},"2020-05-03":{"SGD":0.018855}}}
```

There are some more examples in: https://github.com/stevecondylios/priceR/issues/21

For reference, here are the `BTN` to `SGD` rates for the last 5 years according to google (note nothing above around 0.22, but the API shows ~1.5):

![image](https://user-images.githubusercontent.com/16319829/94507290-bf994980-0252-11eb-86a0-f7848008b68e.png)

**Comment by stevecondylios** [comment]
Some more examples of incorrect exchange rates mentioned in https://github.com/stevecondylios/priceR/issues/22

On 1 May 2020 the rate given is 1.0945, but on 2 May 2020 the rate is 1701.610429

https://api.exchangerate.host/timeseries?start_date=2020-05-01&end_date=2020-05-02&base=XAU&symbols=USD

```
{"success":true,"timeseries":true,"base":"XAU","start_date":"2020-05-01","end_date":"2020-05-02","rates":{"2020-05-01":{"USD":1.0945},"2020-05-02":{"USD":1701.610429}}}
```

**Comment by Callumr22** [comment]
Hi, @stevecondylios - great package!

Just to let you know that I'm also getting some incorrect codes for Chilean Peso and Colombian Peso in September - December 2019. Exchange rates much higher vs e.g. google finance i.e. they have switched to > 1.00

R Code
-------

test_clp <- historical_exchange_rates("CLP", to = "USD", start_date = period_start_date,
                          end_date = period_end_date)

test_cop <- historical_exchange_rates("COP", to = "USD", start_date = period_start_date,
                                      end_date = period_end_date) 

colnames(test_clp) <- c("Date","Rates")

test_clp %>%
  mutate_at(vars(Date),~as.Date(.)) %>%
  ggplot(aes(x=Date,y=Rates)) +
  geom_line() +
  theme_classic()

colnames(test_cop) <- c("Date","Rates")

test_cop %>%
  mutate_at(vars(Date),~as.Date(.)) %>%
  ggplot(aes(x=Date,y=Rates)) +
  geom_line() +
  theme_classic()

VISUALS
--------

![clp_sep_dec_2019](https://user-images.githubusercontent.com/43612478/100263720-c5a36200-2f45-11eb-80e9-08233bf1ba4b.png)

![cop_sep_dec_2019](https://user-images.githubusercontent.com/43612478/100263723-c76d2580-2f45-11eb-992e-37ab162c2bd6.png)

VALIDATION
--------

![google_finance_clp_sep_2019](https://user-images.githubusercontent.com/43612478/100263700-bde3bd80-2f45-11eb-9e40-30948e0c6cc2.png)

![google_finance_cop_sep_2019](https://user-images.githubusercontent.com/43612478/100263688-bb816380-2f45-11eb-8925-0938205a736e.png)

**Comment by arzzen** [comment]
FYI: Our internal forex rate algorithm has changed from 2020-05-02 and has been switched to a calculation based on midpoint data

**Comment by stevecondylios** [comment]
Hi @arzzen 

I think the discrepancies are far too large to have resulted from a change in calculation method. 

See the [price of gold in USD](https://api.exchangerate.host/timeseries?start_date=2020-05-01&end_date=2020-05-02&base=XAU&symbols=USD):

```json
{"motd":{"msg":"If you or your company use this project or like what we doing, please consider backing us so we can continue maintaining and evolving this project.","url":"https://exchangerate.host/#/donate"},"success":true,"timeseries":true,"base":"XAU","start_date":"2020-05-01","end_date":"2020-05-02","rates":{"2020-05-01":{"USD":1.0945},"2020-05-02":{"USD":1701.610429}}}
```

exchangerate.host says the gold price was $1.0945 on 1 may 2020, but we know the [gold price](https://goldprice.org/gold-price-history.html) never got below $1000USD in the past 10 years:

![image](https://user-images.githubusercontent.com/16319829/103719522-4c575e80-501d-11eb-97be-130a6cc92420.png)

Here is the Gold price in USD directly from exchangerate.host over the last 11 years:

![image](https://user-images.githubusercontent.com/16319829/103718559-1d3fed80-501b-11eb-8ee1-541213139406.png)

From 2 May 2020 onwards, the data from exchangerate.host API looks correct, but values prior to 2 May 2020 are a _**long**_ way off what other sources report.
