### ISSUE TITLE
Access Restricted - despite the plan

### ISSUE THREAD

**Issue by cubasepp** [Formicka/exchangerate.host#241]
Hi,

I get:

```
{
  success: false, 
  error: {
    code: 105,
      type: "source_currency_access_restricted",
      info: "Access Restricted - Your current Subscription Plan does not support Source Currency Switching."
  }
}
```
on following call:
> https://api.exchangerate.host/timeframe?access_key=key&start_date=2023-08-01&end_date=2023-08-31&source=EUR&currencies=USD

I am on the PROFESSIONAL PLUS Plan.
Can I fix this somehow by my self?

I wrote to support@apilayer.com and this is not responding as fast as I need (weekend)

BTW: support@exchangerate.host does not work - so get wrong configured E-Mail Server back.

**Comment by alerque** [comment]
I suspect you're just using old code based on examples in this repository. The support email and such you mention are all old.

This project got sold off (with no announcement) to a 3rd party which is now running it using completely different data and code from the one that used to run it, and it now doesn't seem to have anything to do with what is documented here. The API endpoints are all different, probably copied from one of their other projects.

**Comment by cubasepp** [comment]
This is already the stuff from the new provider.

but good to know, that this is the wrong places. :)

**Comment by alerque** [comment]
Ya I could be wrong but I haven't seen the slightest sign the new provider has any interest in this repository.
