### ISSUE TITLE
Currencies Returns "0"

### ISSUE THREAD

**Issue by kubradts** [Formicka/exchangerate.host#29]
Hey Hi ,
I started to use your fixer currency api , but sometimes I got all currencies returns "0" so it makes my whole calculation 0  after I multiple my values their native currencies. Can you explain what is the reason behind that . I m thinking Im requesting too much  as a result of that I got no response.. Please let me know and how to fix it.

**Comment by arzzen** [comment]
hi @kubradts, yes there is a request limit, you can see it in the response header.
I recommend you to cache your requests
