### ISSUE TITLE
max rate of demands?

### ISSUE THREAD

**Issue by daenuthelawyer** [Formicka/exchangerate.host#30]
Hei.
Thanks for this great api. I am using it through a third party interface to convert some 3000 currencies. After about one hundred I get the HTTP error 429, even after putting in a 1s sleep between requests. Is there a maximum number of requests per Minute to be aware of? If so, is this in the documentation - I have not seen it. Is there a robot.txt?
Best, Dan

**Comment by arzzen** [comment]
hi @daenuthelawyer , yes there is a request limit, you can see it in the response header.
I recommend you to cache your requests.
btw, thank you for asking, I will add to the documentation.

**Comment by daenuthelawyer** [comment]
@arzzen Perfect, thanks.
