### ISSUE TITLE
Accept more donation types

### ISSUE THREAD

**Issue by magnuschatt** [Formicka/exchangerate.host#39]
I want to donate cryptocurrencies to you guys, but I don't want to also "donate" money to the miners in the form of fees. I recommend NowPayments as they would allow for feeless donations with [NANO](https://nano.org/) together with a wealth of other cryptocurrencies: 

Here is a quick guide on how to add a donation button to your website:
https://www.youtube.com/watch?v=6pfom6D-9QU

**Comment by arzzen** [comment]
@magnuschatt Thank you for your interest, I appreciate it! I just added a donate button there.

**Comment by magnuschatt** [comment]
@arzzen That's cool! I don't see NANO in the list of currencies though. Also, it looks like the search is broken. All currencies disappear when you type something. Not sure if your mistake or NowPayments.

**Comment by arzzen** [comment]
> @arzzen That's cool! I don't see NANO in the list of currencies though. Also, it looks like the search is broken. All currencies disappear when you type something. Not sure if your mistake or NowPayments.

weird, I see NANO there

![obrázok](https://user-images.githubusercontent.com/6382002/116791782-d5a70b00-aabc-11eb-87df-079d781f388d.png)

**Comment by mtotschnig** [comment]
Trying to use the "Donate crypto" button. After selecting currency, and amount, I see the following screen, which is confusing: I am not sure why the donator should provide a social link, and it does not mention ExchangeRate.host anywhere, so I am unsure if it is safe to trust, that money sent via this service would be routed to you. Might this be due to some missing configuration ?
![grafik](https://user-images.githubusercontent.com/1485456/232467959-7444e22f-2594-4d2a-841e-14b6f8dbe872.png)

**Comment by arzzen** [comment]
> Trying to use the "Donate crypto" button. After selecting currency, and amount, I see the following screen, which is confusing: I am not sure why the donator should provide a social link, and it does not mention ExchangeRate.host anywhere, so I am unsure if it is safe to trust, that money sent via this service would be routed to you. Might this be due to some missing configuration ? 

@mtotschnig this is our official link for donations via crypto https://nowpayments.io/donation?api_key=SMHBNKR-MYRMBFK-PHXAAHK-3GP6TZA - it's seems theirs UI are have some latency for loading - just wait couple of seconds for load all the currencies or maybe use another browser (for me it's working on firefox and chrome correctly).

Meantime I will try find another (stable and more trusted) donation service for crypto...

**Comment by mtotschnig** [comment]
@arzzen The first page renders correctly for me as well. It is what I get after clicking the Next button  which looks confusing.

**Comment by mtotschnig** [comment]
@arzzen Just sent BTC 0.0017. I hope you get credited for it.

**Comment by arzzen** [comment]
credited, thank you I appreciate it
