### ISSUE TITLE
We are investigating reports of degraded performance issues and we are working on it

### ISSUE THREAD

**Issue by arzzen** [Formicka/exchangerate.host#43]
fyi: api is under ddos attack

**Comment by arzzen** [comment]
This incident has been resolved.

**Comment by yurist38** [comment]
I can confirm the issue. `https://api.exchangerate.host/latest?base=usd ` returns 404. Also, I've noticed that the [status page](https://exchangerate.host/#/status) doesn't show any information.

**Comment by mcarans** [comment]
I saw this issue yesterday, it went away but has reemerged this morning (here in NZ).

**Comment by arzzen** [comment]
The server was under active DDoS attack, currently, the service is coming online... #44

**Comment by mcarans** [comment]
The API is still down for me - I get "api.exchangerate.host took too long to respond."
