### ISSUE TITLE
Response showing old date

### ISSUE THREAD

**Issue by DeepFriedPotato** [Formicka/exchangerate.host#55]
When querying [https://api.exchangerate.host/latest?base=USD], sometimes I get a response with a date several days old. For example, it's May 27 today, and I'm getting 2021-05-18 in the "date" field. This happens some of the times, on some devices. Removing "?base=USD" fixes the issue.

**Comment by arzzen** [comment]
@DeepFriedPotato hm, you can try to add an additional parameter `&v=<actual_date>` in the query, where `<actual_date>` enter the day in the format for example `Y-m-d` (or you can add only hour value)

**Comment by DeepFriedPotato** [comment]
I noticed that simply using [https://api.exchangerate.host/latest?base=USD&v=] fixes the problem. I'm a little bit wary of using this because it's not documented, and seems like a workaround. Are there plans to fix the bug? Thank you so much for providing the free service!

**Comment by arzzen** [comment]
Added notice to faq section called "Response showing old date" to site
