### ISSUE TITLE
Rate limit

### ISSUE THREAD

**Issue by Thav0** [Formicka/exchangerate.host#58]
Hello

I want to know how many request I can do per day / hour
I searched on the website, however I didn't find nothing about

Best

**Comment by arzzen** [comment]
Hi @Thav0 , yes there are limits, rate limits are described in the response header.
Please respect the rate limit, and cache your requests (at least for 6 hours). 
(Exchange rates are updated once every 12 hours each day.)

btw there are faq about rete limits see https://exchangerate.host/#/#faq -> "Rate Limits" section
