### ISSUE TITLE
Old date with USD & EUR

### ISSUE THREAD

**Issue by sal0max** [Formicka/exchangerate.host#59]
Hi, depending on the base currency, the response features an old date.

Here, everything is fine:
https://api.exchangerate.host/latest -> 2021-06-17

However, with `USD` and `EUR` the date is old:
https://api.exchangerate.host/latest?base=USD -> 2021-06-13
https://api.exchangerate.host/latest?base=EUR -> 2021-06-14

But that's only the case with the default source. Take `ecb`, `boc` or `rba` and it's up-to-date, again:
https://api.exchangerate.host/latest?base=USD&source=ecb -> 2021-06-17
https://api.exchangerate.host/latest?base=USD&source=boc -> 2021-06-17
https://api.exchangerate.host/latest?base=USD&source=rba -> 2021-06-17
https://api.exchangerate.host/latest?base=EUR&source=ecb -> 2021-06-17

Can you look into this?

**Comment by arzzen** [comment]
See notice in the faq section called "Response showing old date" (#55)

```
 API requests are cached by default. You can try to add an additional parameter &v=_actual_date_ in the query, where _actual_date_ enter the day in the format for example Y-m-d (or you can add only hour value). 
```
