### ISSUE TITLE
Wrong rates are returned for crypto

### ISSUE THREAD

**Issue by edpiburkhart** [Formicka/exchangerate.host#64]
I would love to use this API, but it seems currently unusable for its main purpose.
When trying to get the exchange rate for BTC, for instance, the return value is just wrong:
<https://api.exchangerate.host/latest?source=crypto&symbols=BTC&base=EUR>
returns:
```json
{
  "motd": {
    "msg": "If you or your company use this project or like what we doing, please consider backing us so we can continue maintaining and evolving this project.",
    "url": "https://exchangerate.host/#/donate"
  },
  "success": true,
  "base": "EUR",
  "date": "2021-07-25",
  "rates": {
    "BTC": 0.000233
  }
}
```
Although the exchange rate is around 1BTC = 30000€.
I am aware of #37, but 1/0.00023=4292 so it is not just an issue of inverted rate.

**Comment by Galang23** [comment]
I don't think this is a bug, but the base and target currency are swapped. Using request provided https://api.exchangerate.host/latest?source=crypto&symbols=BTC&base=EUR returns 0.000026 as of 13 August 2021 server time. When BTC and EUR is swapped, the result is 38490.5 in server time.

```json
GET https://api.exchangerate.host/latest?source=crypto&symbols=BTC&base=EUR
{
  "motd": {
    "msg": "If you or your company use this project or like what we doing, please consider backing us so we can continue maintaining and evolving this project.",
    "url": "https://exchangerate.host/#/donate"
  },
  "success": true,
  "base": "EUR",
  "date": "2021-08-13",
  "rates": {
    "BTC": 0.000026
  }
}

GET https://api.exchangerate.host/latest?source=crypto&symbols=EUR&base=BTC
{
  "motd": {
    "msg": "If you or your company use this project or like what we doing, please consider backing us so we can continue maintaining and evolving this project.",
    "url": "https://exchangerate.host/#/donate"
  },
  "success": true,
  "base": "BTC",
  "date": "2021-08-13",
  "rates": {
    "EUR": 38490.5
  }
}
```

**Comment by arzzen** [comment]
@edpiburkhart you can try to add an additional parameter `&v=<actual_date>` in the query, where `<actual_date>` enter the day in the format for example `Y-m-d` (or you can add only hour value) because API requests are cached by default. 

ps: See notice in the faq section called "Response showing old date" (#55)
