### ISSUE TITLE
BTC rates are wrong

### ISSUE THREAD

**Issue by Applitom** [Formicka/exchangerate.host#65]
Hello,
Thank you for this great API, I Love it 🙏🏻

It Seems like BTC rates are wrong using this endpoint:
[https://api.exchangerate.host/latest?base=USD&symbols=BTC](https://api.exchangerate.host/latest?base=USD&symbols=BTC)
return the following rates which seem to be wrong
`{
   "success":true,
   "base":"USD",
   "date":"2021-07-31",
   "rates":{
      "BTC": 0.000273
   }
}`

According to google BTC rate as of today (Jul-31) is 0.000024 
Thanks you

**Comment by arzzen** [comment]
Hi, @Applitom 
Thanks for reporting an error, it is currently fixed
https://api.exchangerate.host/latest?base=USD&symbols=BTC&v=1

**Comment by Applitom** [comment]
Thank you dir the fix @arzzen
What does the parameter v mean?
Is it mandatory?

**Comment by arzzen** [comment]
@Applitom v parameter is not mandatory, and has no specific meaning (does not do anything :) )
