### ISSUE TITLE
Extend the maximum timeseries length to 366 days

### ISSUE THREAD

**Issue by jgough** [Formicka/exchangerate.host#67]
The end-user code required to download historical data over a number of years is slightly complex at the moment.  It could be made _far_ simpler if the maximum timeseries length were extended by just an extra day to 366 days to account for leap years.

The pseudocode logic I'd like to be able to use is
```
for year in range(2017,2021):
    download data from 1st Jan to 31st Dec
```

Unfortunately I can't use this code with the limit of 365 days as this fails on leap years and misses the 31st Dec.
So the code required to do this at the moment involves taking a start date, doing a bunch of date math adding 365 days, keeping track of start and end dates and and iterating over that.  Not as clean.

A change to allow 366 days would just make code simpler!

**Comment by arzzen** [comment]
hi, @jgough I modified the maximum number of days to 366.

you can check it using `jq` as follows:
`curl -s "https://api.exchangerate.host/timeseries?start_date=2020-01-01&end_date=2021-02-04&symbols=USD,EUR" | jq '.rates | length'`

**Comment by jgough** [comment]
Thank you so much!
