### ISSUE TITLE
Wrong data for EURUSD on 2021-07-15

### ISSUE THREAD

**Issue by DavidKarlas** [Formicka/exchangerate.host#68]
[API](https://api.exchangerate.host/2021-07-15?base=EUR&symbols=USD) is returning 1.181425
[ECB](https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/eurofxref-graph-usd.en.html) says its 1.1809

**Comment by sal0max** [comment]
Right now (2021-08-11 22:42 UTC), these are the rates EUR -> USD, of several trusted services:

| service                      | conversion rate
|---------------------|----------
| Google/Morningstar | 1,17
| ECB                           | 1,1718
| finance.yahoo.com   | 1,1739
| xe.com                      | 1,17394
| wise.com                  | 1,17395
| bloomberg.com        | 1,1740
| libertex.com             | 1,17407
| boerse-frankfurt.de | 1,1742

The max difference between all these services is 0,0024.
Your issue states a difference of 0,000525.

The exchangerate.host website states _"Currency data delivered are sourced from financial data providers and banks, including the European Central Bank."_
As I read it, exchange rates are calculated based on a variety of sources. Hence the slight difference to the ECB values.

There is no single true value in exchange rates.
In my opinion, there is no error, here.
