### ISSUE TITLE
Server is down (Error 521)

### ISSUE THREAD

**Issue by sal0max** [Formicka/exchangerate.host#72]
Only calls cashed by Cloudflare work (https://api.exchangerate.host/latest).

For "fresh" requests, with an unique `v` parameter (e.g. https://api.exchangerate.host/latest?v=123712371273127312731723172), an error is returned: ` Error 521 Web server is down`

**Comment by rajakhoury** [comment]
I have been facing the same error today calling this endpoint `https://api.exchangerate.host/convert?from=%s&to=%s`

**Comment by berrymore** [comment]
It doesn't work with a list of `symbols` for me.

Still works: https://api.exchangerate.host/latest?base=USD&symbols=RUB
Doesn't work: https://api.exchangerate.host/latest?base=USD&symbols=RUB,EUR

**Comment by arzzen** [comment]
I apologize for the temporary outage caused by the server provider (caused by frozen cisco). 
Now everything should work fine.

**Comment by sal0max** [comment]
Can confirm it's working again. 👍 
Thanks a lot!

Closing this now.

**Comment by vofack** [comment]
Hi everyone, am facing the same issue today ! 

https://api.exchangerate.host/latest?/source=ecb&base=CAD&v=2022/12/20  ==> 521 error

Any update please ?!
