### ISSUE TITLE
Question: What timezone is this api working in?

### ISSUE THREAD

**Issue by sal0max** [Formicka/exchangerate.host#74]
When I query https://api.exchangerate.host/latest this is part of the response:

```json
...
date: "2021-09-04"
...
```
When will this date jump to the next day? 0:00 UTC?
Same question for historic rates.

**Comment by mezhevikin** [comment]
I have the same question.

Sometimes at the night I have an error:

`Client error: `GET https://api.exchangerate.host/latest?base=USD&v=2021-12-14` resulted in a `404 Not Found` response:` 

I think this problem related with timezone.

**Comment by pinarkaymaz6** [comment]
I have the same question, could anyone let me know what's the timezone for the `date` in the response?
