### ISSUE TITLE
Incorrect rates?

### ISSUE THREAD

**Issue by KirovAir** [Formicka/exchangerate.host#75]
Currently the currency for USD as base, EUR = 0.825786.
https://api.exchangerate.host/latest?base=USD

When checking google or any other exchange it hovers around 0.84, 0.85.

Am I missing something?

**Comment by arzzen** [comment]
See notice in the faq section called "Response showing old date" (#55, #59, #62)
`API requests are cached by default. You can try to add an additional parameter &v=_actual_date_ in the query, where _actual_date_ enter the day in the format for example Y-m-d (or you can add only hour value). `

**Comment by KirovAir** [comment]
Thanks for responding, much appreciated! Also thanks for providing this service. :)
