### ISSUE TITLE
Is Conversion API Down? "Error 521: Web server is down"

### ISSUE THREAD

**Issue by sameerkumar18** [Formicka/exchangerate.host#80]
Hi, I've been using this API for a while now, and suddenly few mins ago the API stopped working and threw an error: "Error 521: Web server is down
<img width="1370" alt="Screenshot 2021-10-04 at 11 25 20 AM" src="https://user-images.githubusercontent.com/15978864/135800884-083c26a1-c14b-4c7c-a5e2-19e730a5f89b.png">
"

**Comment by Admolly** [comment]
Likewise.  Stopped working this morning for me as well.

**Comment by arzzen** [comment]
I apologize for the temporary outage.
Now everything should work fine.

**Comment by Admolly** [comment]
Thanks for the quick turnaround!
