### ISSUE TITLE
Error 521 - response to /latest with multiple symbols parameters

### ISSUE THREAD

**Issue by cymbolz** [Formicka/exchangerate.host#84]
Response status 521 from /latest when passing multiple (comma separated) symbols parameters.

This works ok:
https://api.exchangerate.host/latest?base=AUD&symbols=USD

This does not:
https://api.exchangerate.host/latest?base=AUD&symbols=USD,SGD

**Comment by aryanjaya** [comment]
Same Issue here.

But for me always error when include symbols in query parameter.
example:
https://api.exchangerate.host/latest?symbols=SGD
https://api.exchangerate.host/latest?symbols=MYR

**Comment by lequangminh** [comment]
Please fix

**Comment by julienarcin** [comment]
Same with conversion:
https://api.exchangerate.host/convert?from=USD&to=EUR&amount=50

**Comment by arzzen** [comment]
I apologize for the temporary outage.
Now everything should work fine.

**Comment by julienarcin** [comment]
No need to apologize for a free service.

Thanks for the great work and great support 👍👍👍
