### ISSUE TITLE
how much back in time historical data is working ? 

### ISSUE THREAD

**Issue by tigran10** [Formicka/exchangerate.host#86]
Hey there, thanks for a lovely API. 

A quick question, how much back historical API is working ?

I get result for 2020-05-11

```
curl https://api.exchangerate.host/convert\?from\=USD\&to\=AMD\&date\=2020-05-11\&amount\=100 | jq .
```

but get I get null 2020-04-11

```
 curl https://api.exchangerate.host/convert\?from\=USD\&to\=AMD\&date\=2020-04-11\&amount\=1 | jq .
```

**Comment by arzzen** [comment]
Hi @ tigran10, for each source you can see the date availability here https://api.exchangerate.host/sources (attribute `available_from_date`), forex data is available from 2020-05-05

**Comment by tigran10** [comment]
thanks @arzzen
