### ISSUE TITLE
http access

### ISSUE THREAD

**Issue by luissalasmarmol** [Formicka/exchangerate.host#87]
I'm using this service from an old program that is not able to read https url's, so I created a http version of your page through a "gateway" using addresses like this; 

"http://api.exchangerate.host.proxy._ourdomain_.com/convert?from=GBP&to=EUR&amount=120" 

to obtain the data from

"http://api.exchangerate.host/convert?from=GBP&to=EUR&amount=120" 

But now I receive this message:

502 Bad Gateway nginx/1.21.3

Is it possible to avoid that? I am willing to donate the amount you consider necessary to activate this route.

Regards

LS

**Comment by arzzen** [comment]
Hi @luissalasmarmol , from now you can use http instead of https (if you like)

eg
```
curl -I "http://api.exchangerate.host/convert?from=GBP&to=EUR&amount=1200"
HTTP/1.1 200 OK
Date: Tue, 23 Nov 2021 11:17:36 GMT
```

Every donation (in the amount you deem appropriate) will please and, of course, take this service one step further ;)

**Comment by luissalasmarmol** [comment]
Thank you very much Lukáš,

I have donated € 50. It's not much, but there are at least 25 large
cappuccinos. The truth is that we use the service very residual. If we get
to make an important use (as I expect) I will come back to donate more...

I am not having a good time, but if you have problems to continue with the
website, contact me, maybe then I am at a better time

All the best

LS

**Comment by arzzen** [comment]
@luissalasmarmol Thank you!
