### ISSUE TITLE
latest?base=USD has old data

### ISSUE THREAD

**Issue by mezhevikin** [Formicka/exchangerate.host#88]
https://api.exchangerate.host/latest?base=USD has old data for (2021-08-29)

**Comment by arzzen** [comment]
Hi, @mezhevikin 
See notice in the faq section called "Response showing old date" (#55, #75, #62, #59, #64)

```
 API requests are cached by default. You can try to add an additional parameter &v=_actual_date_ in the query, where _actual_date_ enter the day in the format for example Y-m-d (or you can add only hour value). 
```

**Comment by mezhevikin** [comment]
@arzzen Hi. I followed your recommendation and added` 'v' => date("Y-m-d") ` to url . But sometimes (at night) I have errors from server : 

`Client error: `GET https://api.exchangerate.host/latest?base=USD&v=2021-12-14` resulted in a `404 Not Found` response:` 

Which timezone do I need?

**Comment by arzzen** [comment]
Hi

The API delivers EOD / End of Day historical exchange rates, which become
available at 00:05am CET for the previous day .

*Timezone: Europe/Frankfurkt*


Dňa ut 14. 12. 2021, 8:09 Mezhevikin Alexey ***@***.***>
napísal(a):

**Comment by maysaleba** [comment]
Hi,

Can you please explain what exactly is meant by  'or you can add only hour value' in the FAQ? what format do i have to put in to use hour value?

**Comment by arzzen** [comment]
> Hi,
> 
> Can you please explain what exactly is meant by 'or you can add only hour value' in the FAQ? what format do i have to put in to use hour value?

For example: `https://api.exchangerate.host/latest?base=USD&v=2021-12-29T15` where you can change value of `v=` parameter to actual date with hour part to break cache
